code_type: "php"
require: "rpg2d"
description: |-
    Всемирно неизвестная игра Игорь создана для демоснтрации работы сервиса. С игрой так же идет клиентская часть на игровом двжике Unity (доступна версия для телефонов и ПК). Вы можете изменять код на свое усмотрение, коммерческое использование без согласования запрещено.