code_type: "php"
require: "rpg2d"
description: |-
    2D MMORPG игра Игорь создана для демоснтрации работы сервиса (https://github.com/webrobot1/igor-server). С игрой так же идет клиентская часть на игровом двжике Unity (https://github.com/webrobot1/igor-unity) для мобильных устрйоств и ПК. Вы можете изменять код на свое усмотрение, коммерческое использование без согласования запрещено.