code_type: "php"
image: "http://my-fantasy.ru/theme/custom/frontend/images/games/igor.png"
framework: "rpg2d"
libraries: ["pathfinding", "entitys"]
name: "Игорь"
description: |-
    2D MMORPG игра Игорь создана для демоснтрации работы сервиса (https://github.com/webrobot1/igor-server). С игрой так же идет клиентская часть на игровом двжике Unity (https://github.com/webrobot1/igor-unity) для мобильных устрйоств и ПК. Вы можете изменять код на свое усмотрение, коммерческое использование без согласования запрещено.