type: json
default: |-
    {
        "joystick":
        {
            "type":"checkbox",
            "title":"Джойстик", 
            "value":1
        },        
        "autoattack":
        {
            "type":"checkbox",
            "title":"Авто атака", 
            "value":1
        }, 
        "actions":
        {
            "type":"dropdown", 
            "title":"Быстрый доступ",  
            "value":"mobile",
            "values":{"mobile":"Мобильная", "pc":"ПК"}
        }, 
        "radius":
        {
            "type":"slider", 
            "title":"Радиус обзора", 
            "min":10, 
            "max":45, 
            "value":10
        },     
        "fps":
        {
            "type":"slider", 
            "title":"FPS (частота приема пакетов)", 
            "min":30, 
            "max":100, 
            "value":60
        }
    }
entitys: players